#!/usr/bin/env python3
from lookup import *
from helper import *

ws = workspace[4]
focus(ws)

# Start RubyMine
cmd = [
    'dex',
    '/usr/share/applications/jetbrains-rubymine.desktop',
]
if workspace_contains(ws, name="RubyMine"):
    pass
else:
    start(cmd)

# Start Chrome
cmd = [
    'dex',
    '/home/matt/.local/share/applications/google-chrome-work.desktop',
    'https://github.com/ScriptRock?tab=repositories',
]
"""
if workspace_contains(ws, name="Chrome"):
    # Open in new tabs
    cmd += ['--new-tab']
else:
    # Open in new tabs
    cmd += ['--new-window']
cmd += [
    "--user-data-dir=.config/google-chrome/Profile 1"
]
cmd += pages
"""

start(cmd)
