#!/usr/bin/env python3
import i3ipc
import sys
from subprocess import Popen
from lookup import *
from helper import *

ws = workspace[8]
title = "Chrome"
pages = [
    'http://podbay.fm',
]

i3 = i3ipc.Connection()
tree = i3.get_tree()

i3.command("Workspace {}".format(ws))

cmd = [
    '/opt/google/chrome/google-chrome',
]

if workspace_contains(ws, name=title):
    # Open in new tabs
    cmd += ['--new-tab']
else:
    # Open in new tabs
    cmd += ['--new-window']

cmd += [
    '--user-data-dir=.config/google-chrome/Default'
]
cmd += pages

Popen(cmd)
