#!/bin/bash

pa="pactl"

function output () {
    sink=`pactl list short sinks | grep $1 | cut -f1`
    echo "Setting default sink to `pactl list short sinks | grep $1`...";
    "$pa" set-default-sink $1
    echo "Moving current inputs to default sink..."
    "$pa" list short sink-inputs | while read line
    do
        echo "Moving input: ";
        echo $line | cut -f1 -d' ';
        echo "to sink: $1";
        "$pa" move-sink-input `echo $line | cut -f1 -d' '` "$1"
    done
}

output `pactl list short sinks | awk '/pci.*analog/ {print $2}'`
