#!/bin/bash
# TV & Monitor 90 degrees
xrandr
# xrandr --newmode "1280x720_60.00"  74.48  1280 1336 1472 1664  720 721 724 746  -HSync +Vsync
# xrandr --addmode DP-2 "1280x720_60.00"
xrandr --output DP-1 --mode 1920x1080 --primary --output DP-2 --mode 1920x1080 --rotate left --right-of DP-1
# Monitors
# xrandr --output HDMI-1 --mode 1920x1080 --primary --output HDMI-2 --mode 1920x1200 --rotate left --right-of HDMI-1
/home/matt/.conky/stop.sh
