#!/bin/bash
xrandr --output HDMI-2 --mode 1920x1200 --primary --output HDMI-1 --mode 1920x1080 --same-as HDMI-2 --scale `echo "1920/1920" | bc -l`x`echo "1200/1080" | bc -l`
/home/matt/.conky/stop.sh
