#!/bin/bash
dpath=/home/matt/.i3/scripts/display
displays=$(ls -t "$dpath")

if [ -z $@ ]
then
  # Generate list of display profiles
  echo "$displays"
else
  display=$@
  "$dpath/$display"
  notify-send "Display Profile" "Using display profile '$display'"
fi

# handle_selection "$( echo "$displays" | rofi -dmenu -i -p 'Display Profile ↠ ' -hlbg '#5FA5D7' -bc '#5FA5D7' )"
