#!/bin/bash
ppath=/home/matt/.i3/scripts/profiles
profiles=$(ls -t "$ppath" -I *.py -I __pycache__)

if [ -z $@ ]
then
  # Generate list of profiles
  echo "$profiles"
else
  profile=$@
  "$ppath/$profile"
  notify-send "Profile" "Activating '$profile' profile"
fi

# handle_selection "$( echo "$profiles" | rofi -dmenu -i -p 'Profile ↠ ' -hlbg '#5FA5D7' -bc '#5FA5D7' )"
