#!/bin/bash
vagrant=$(cd /home/matt/src/vagrant;ls -t)
runningvms=$(vboxmanage list runningvms)
vms=$(vboxmanage list vms|cut -d' ' -f 1|sed 's/"//g')

handle_selection() {
  if [[ $1 ]]; then
    name=$1
    if grep -q "$name" <<< `vboxmanage list runningvms`; then
      notify-send -i virtualbox "Already Running" "VM $name already running"
    else
      msg="Starting VM"

      notify-send -i virtualbox "$msg" "$name"

      vboxmanage startvm "$name" &
    fi
  fi
}

handle_selection "$( echo "$vms" | rofi -dmenu -i -p 'VM ↠ ' -hlbg '#5FA5D7' -bc '#5FA5D7' )"
